<?php

namespace TestsLoginMemoryPersistent\Application;

use LoginMemoryPersistent\Application\CreateUser;
use LoginMemoryPersistent\Domain\Exceptions\DuplicatedUserException;
use LoginMemoryPersistent\Domain\Repository\UserSaveRepositoryInterface;
use LoginMemoryPersistent\Domain\Repository\UserSearchRepositoryInterface;

class CreateUserTest extends \PHPUnit_Framework_TestCase
{
    protected $userSearchRepository;
    protected $userSaveRepository;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->userSearchRepository = $this
            ->getMockBuilder(UserSearchRepositoryInterface::class)
            ->disableOriginalConstructor()
            ->getMock();

        $this->userSaveRepository = $this
            ->getMockBuilder(UserSaveRepositoryInterface::class)
            ->disableOriginalConstructor()
            ->getMock();
    }

    public function testCreateCorrectlyUser() {
        $createUserUseCase = new CreateUser($this->userSaveRepository);

        $this->userSaveRepository
            ->expects($this->once())
            ->method('save');

        $this->assertTrue($createUserUseCase->addUser('user','password'));
    }

    public function testDuplicatedUserCreation() {
        $createUserUseCase = new CreateUser($this->userSaveRepository);

        $this->userSaveRepository
            ->expects($this->once())
            ->method('save')
            ->will($this->throwException(new DuplicatedUserException()));

        $this->expectException(DuplicatedUserException::class);
        $createUserUseCase->addUser('user','password');
    }
}
